
version: '3.8'

services:
  server:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      # Volume the config for nginx -> :ro read only
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    build:
      context: ./Dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    # ports:
    #   - "3000:9000"
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    env_file:
      - ./env/mysql.env
    ports:
      - "3306:3306"
    # volumes:
    #   - mysql_data:/var/lib/mysql
  composer:
    build:
      context: ./Dockerfiles
      dockerfile: composer.dockerfile
    container_name: laravel_composer
    volumes:
      - ./src:/var/www/html
    # entrypoint: ["composer", "--ignore-platform-reqs"]

  artisan:
    build:
      context: ./Dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
  npm:
    image: node
    working_dir: /var/www/html
    entrypoint: ['npm']
    volumes:
      - ./src:/var/www/html

  
#  docker compose run --rm --build composer laravel new example-app .